# Generated by Django 3.0.3 on 2020-03-31 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarma',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alarma',
            name='usuario',
        ),
        migrations.AddField(
            model_name='alarma',
            name='cantidad',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='alarma',
            name='hora',
            field=models.TimeField(default='01:45', null=True),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.Medicamento'),
        ),
    ]
