# Generated by Django 3.0.3 on 2020-03-05 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alarma_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.Medicamento'),
        ),
        migrations.AddField(
            model_name='alarma',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.Usuario'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.Usuario'),
        ),
    ]
