# Generated by Django 3.0.3 on 2020-03-31 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alarma_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarma',
            name='estado',
        ),
        migrations.AddField(
            model_name='alarma',
            name='cantidad',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='alarma',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='alarma',
            name='medicamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.Medicamento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo_dosis',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('ml', 'ml'), ('Ul', 'Ul'), ('mcg', 'mcg'), ('mcg/ml', 'mcg/ml'), ('mEq', 'mEq'), ('%', '%'), ('mg/g', 'mg/g'), ('mg/cm2', 'mg/cm2'), ('mg/ml', 'mg/ml'), ('mcg/hora', 'mcg/hora')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.Usuario'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
