# Generated by Django 3.0.3 on 2020-03-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20200304_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
    ]
