# Generated by Django 3.0.3 on 2020-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20200331_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='hora',
            field=models.TimeField(default='00:12', null=True),
        ),
    ]
