# Generated by Django 3.0.3 on 2020-03-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20200304_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='tipo_dosis',
            field=models.CharField(choices=[('g', 'g'), ('mg', 'mg'), ('ml', 'ml'), ('Ul', 'Ul'), ('mcg', 'mcg'), ('mcg/ml', 'mcg/ml'), ('mEq', 'mEq'), ('%', '%'), ('mg/g', 'mg/g'), ('mg/cm2', 'mg/cm2'), ('mg/ml', 'mg/ml'), ('mcg/hora', 'mcg/hora')], max_length=200, null=True),
        ),
    ]
