# Generated by Django 3.0.3 on 2020-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_medicamento_tipo_dosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
